spring:
  application:
    name: rooms-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: rooms
  profiles:
    active: production

management:
  metrics:
    export:
      prometheus:
        enabled: true
      wavefront:
        apiToken: ""
        enabled: false
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        # include all endpoints
        include: "*"
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
