spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: visits
  profiles:
    active: production

management:
  metrics:
    export:
      wavefront:
        apiToken: ""
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true

  endpoints:
    web:
      exposure:
        # include all endpoints
        include: "*"
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
