---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rooms-service
  name: rooms-service
  namespace: spring-petclinic
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: rooms-service
status:
  loadBalancer: { }
