INSERT IGNORE INTO rooms VALUES (1, '201', 'NORMAL');
INSERT IGNORE INTO rooms VALUES (2, '101', 'NORMAL');
INSERT IGNORE INTO rooms VALUES (3, '303', 'SPECIAL1');
INSERT IGNORE INTO rooms VALUES (4, '404', 'SPECIAL2');
INSERT IGNORE INTO rooms VALUES (5, '123', 'SPECIAL3');
INSERT IGNORE INTO rooms VALUES (6, '420', 'SPECIAL1');
